ce-- MEMBER INSERT
INSERT INTO idme_members (m_no, m_nickname, m_bday, m_id, m_pwd, m_name, m_email, m_phone, m_address, m_type) VALUES (M_NO_SEQ.NEXTVAL,'adm01',TO_DATE('19940101'),'idme_adm01','idme1234','김가율','idme_adm01@idme.com','010-1111-1111','서울시 용산구','A');
INSERT INTO idme_members (m_no, m_nickname, m_bday, m_id, m_pwd, m_name, m_email, m_phone, m_address, m_type) VALUES (M_NO_SEQ.NEXTVAL,'adm02',TO_DATE('19910101'),'idme_adm02','idme1234','김진웅','idme_adm02@idme.com','010-1111-2222','서울시 강서구','A');
INSERT INTO idme_members (m_no, m_nickname, m_bday, m_id, m_pwd, m_name, m_email, m_phone, m_address, m_type) VALUES (M_NO_SEQ.NEXTVAL,'adm03',TO_DATE('19910101'),'idme_adm03','idme1234','진우람','idme_adm03@idme.com','010-1111-3333','서울시 구로구','A');
INSERT INTO idme_members (m_no, m_nickname, m_bday, m_id, m_pwd, m_name, m_email, m_phone, m_address, m_type) VALUES (M_NO_SEQ.NEXTVAL,'mbr01',TO_DATE('19950101'),'idme_mbr01','idme1234','강민경','idme_mbr01@idme.com','010-2222-1111','서울시 마포구','M');
INSERT INTO idme_members (m_no, m_nickname, m_bday, m_id, m_pwd, m_name, m_email, m_phone, m_address, m_type) VALUES (M_NO_SEQ.NEXTVAL,'mbr02',TO_DATE('19970101'),'idme_mbr02','idme1234','고유주','idme_mbr02@idme.com','010-2222-2222','서울시 마포구','M');
INSERT INTO idme_members (m_no, m_nickname, m_bday, m_id, m_pwd, m_name, m_email, m_phone, m_address, m_type) VALUES (M_NO_SEQ.NEXTVAL,'mbr03',TO_DATE('19930101'),'idme_mbr03','idme1234','곽헌섭','idme_mbr03@idme.com','010-2222-3333','서울시 마포구','M');
INSERT INTO idme_members (m_no, m_nickname, m_bday, m_id, m_pwd, m_name, m_email, m_phone, m_address, m_type) VALUES (M_NO_SEQ.NEXTVAL,'mbr04',TO_DATE('19910101'),'idme_mbr04','idme1234','김명규','idme_mbr04@idme.com','010-2222-4444','서울시 마포구','M');
INSERT INTO idme_members (m_no, m_nickname, m_bday, m_id, m_pwd, m_name, m_email, m_phone, m_address, m_type) VALUES (M_NO_SEQ.NEXTVAL,'mbr05',TO_DATE('20220101'),'idme_mbr05','idme1234','김유리','idme_mbr05@idme.com','010-2222-5555','서울시 마포구','M');
INSERT INTO idme_members (m_no, m_nickname, m_bday, m_id, m_pwd, m_name, m_email, m_phone, m_address, m_type) VALUES (M_NO_SEQ.NEXTVAL,'mbr06',TO_DATE('19930101'),'idme_mbr06','idme1234','김준하','idme_mbr06@idme.com','010-2222-6666','서울시 마포구','M');
INSERT INTO idme_members (m_no, m_nickname, m_bday, m_id, m_pwd, m_name, m_email, m_phone, m_address, m_type) VALUES (M_NO_SEQ.NEXTVAL,'mbr07',TO_DATE('19910101'),'idme_mbr07','idme1234','김진호','idme_mbr07@idme.com','010-2222-7777','서울시 마포구','M');
INSERT INTO icdme_members (m_no, m_nickname, m_bday, m_id, m_pwd, m_name, m_email, m_phone, m_address, m_type) VALUES (M_NO_SEQ.NEXTVAL,'mbr08',TO_DATE('19930101'),'idme_mbr08','idme1234','김태환','idme_mbr08@idme.com','010-2222-8888','서울시 마포구','M');
INSERT INTO idme_members (m_no, m_nickname, m_bday, m_id, m_pwd, m_name, m_email, m_phone, m_address, m_type) VALUES (M_NO_SEQ.NEXTVAL,'mbr09',TO_DATE('20220101'),'idme_mbr09','idme1234','김호직','idme_mbr09@idme.com','010-2222-9999','서울시 마포구','M');
INSERT INTO idme_members (m_no, m_nickname, m_bday, m_id, m_pwd, m_name, m_email, m_phone, m_address, m_type) VALUES (M_NO_SEQ.NEXTVAL,'mbr10',TO_DATE('20220101'),'idme_mbr10','idme1234','낭혜륜','idme_mbr10@idme.com','010-3333-1111','서울시 마포구','M');
INSERT INTO idme_members (m_no, m_nickname, m_bday, m_id, m_pwd, m_name, m_email, m_phone, m_address, m_type) VALUES (M_NO_SEQ.NEXTVAL,'mbr11',TO_DATE('20220101'),'idme_mbr11','idme1234','민지환','idme_mbr11@idme.com','010-3333-2222','서울시 마포구','M');
INSERT INTO idme_members (m_no, m_nickname, m_bday, m_id, m_pwd, m_name, m_email, m_phone, m_address, m_type) VALUES (M_NO_SEQ.NEXTVAL,'mbr12',TO_DATE('20220101'),'idme_mbr12','idme1234','박기남','idme_mbr12@idme.com','010-3333-3333','서울시 마포구','M');
INSERT INTO idme_members (m_no, m_nickname, m_bday, m_id, m_pwd, m_name, m_email, m_phone, m_address, m_type) VALUES (M_NO_SEQ.NEXTVAL,'mbr13',TO_DATE('19970101'),'idme_mbr13','idme1234','박성수','idme_mbr13@idme.com','010-3333-4444','서울시 마포구','M');
INSERT INTO idme_members (m_no, m_nickname, m_bday, m_id, m_pwd, m_name, m_email, m_phone, m_address, m_type) VALUES (M_NO_SEQ.NEXTVAL,'mbr14',TO_DATE('19900101'),'idme_mbr14','idme1234','서형원','idme_mbr14@idme.com','010-3333-5555','서울시 마포구','M');
INSERT INTO idme_members (m_no, m_nickname, m_bday, m_id, m_pwd, m_name, m_email, m_phone, m_address, m_type) VALUES (M_NO_SEQ.NEXTVAL,'mbr15',TO_DATE('20220101'),'idme_mbr15','idme1234','오승우','idme_mbr15@idme.com','010-3333-6666','서울시 마포구','M');
INSERT INTO idme_members (m_no, m_nickname, m_bday, m_id, m_pwd, m_name, m_email, m_phone, m_address, m_type) VALUES (M_NO_SEQ.NEXTVAL,'mbr16',TO_DATE('19930101'),'idme_mbr16','idme1234','오유미','idme_mbr16@idme.com','010-3333-7777','서울시 마포구','M');
INSERT INTO idme_members (m_no, m_nickname, m_bday, m_id, m_pwd, m_name, m_email, m_phone, m_address, m_type) VALUES (M_NO_SEQ.NEXTVAL,'mbr17',TO_DATE('20220101'),'idme_mbr17','idme1234','위혜진','idme_mbr17@idme.com','010-3333-8888','서울시 마포구','M');
INSERT INTO idme_members (m_no, m_nickname, m_bday, m_id, m_pwd, m_name, m_email, m_phone, m_address, m_type) VALUES (M_NO_SEQ.NEXTVAL,'mbr18',TO_DATE('19900101'),'idme_mbr18','idme1234','이동영','idme_mbr18@idme.com','010-3333-9999','서울시 마포구','M');
INSERT INTO idme_members (m_no, m_nickname, m_bday, m_id, m_pwd, m_name, m_email, m_phone, m_address, m_type) VALUES (M_NO_SEQ.NEXTVAL,'mbr19',TO_DATE('19900101'),'idme_mbr19','idme1234','이동헌','idme_mbr19@idme.com','010-4444-1111','서울시 마포구','M');
INSERT INTO idme_members (m_no, m_nickname, m_bday, m_id, m_pwd, m_name, m_email, m_phone, m_address, m_type) VALUES (M_NO_SEQ.NEXTVAL,'mbr20',TO_DATE('20220101'),'idme_mbr20','idme1234','이준엽','idme_mbr20@idme.com','010-4444-2222','서울시 마포구','M');
INSERT INTO idme_members (m_no, m_nickname, m_bday, m_id, m_pwd, m_name, m_email, m_phone, m_address, m_type) VALUES (M_NO_SEQ.NEXTVAL,'mbr21',TO_DATE('20220101'),'idme_mbr21','idme1234','이혜지','idme_mbr21@idme.com','010-4444-3333','서울시 마포구','M');
INSERT INTO idme_members (m_no, m_nickname, m_bday, m_id, m_pwd, m_name, m_email, m_phone, m_address, m_type) VALUES (M_NO_SEQ.NEXTVAL,'mbr22',TO_DATE('19940101'),'idme_mbr22','idme1234','전창현','idme_mbr22@idme.com','010-4444-4444','서울시 마포구','M');
INSERT INTO idme_members (m_no, m_nickname, m_bday, m_id, m_pwd, m_name, m_email, m_phone, m_address, m_type) VALUES (M_NO_SEQ.NEXTVAL,'mbr23',TO_DATE('19950101'),'idme_mbr23','idme1234','조아빈','idme_mbr23@idme.com','010-4444-5555','서울시 마포구','M');
INSERT INTO idme_members (m_no, m_nickname, m_bday, m_id, m_pwd, m_name, m_email, m_phone, m_address, m_type) VALUES (M_NO_SEQ.NEXTVAL,'mbr24',TO_DATE('19990101'),'idme_mbr24','idme1234','주민준','idme_mbr24@idme.com','010-4444-6666','서울시 마포구','M');
INSERT INTO idme_members (m_no, m_nickname, m_bday, m_id, m_pwd, m_name, m_email, m_phone, m_address, m_type) VALUES (M_NO_SEQ.NEXTVAL,'mbr25',TO_DATE('20220101'),'idme_mbr25','idme1234','최아연','idme_mbr25@idme.com','010-4444-7777','서울시 마포구','M');
INSERT INTO idme_members (m_no, m_nickname, m_bday, m_id, m_pwd, m_name, m_email, m_phone, m_address, m_type) VALUES (M_NO_SEQ.NEXTVAL,'mbr26',TO_DATE('19970101'),'idme_mbr26','idme1234','최재혁','idme_mbr26@idme.com','010-4444-8888','서울시 마포구','M');

commit;

-- GOODS INSERT
INSERT INTO IDME_GOODS (G_NO, G_NAME, G_CONTENT, G_PRICE, G_TYPE, G_PHOTO, M_NO) VALUES(G_NO_SEQ.NEXTVAL,'말랑콩떡','말랑말랑한 콩떡'||CHR(10)||CHR(13)||'쫀득쫀득 정말 맛있어요!','3000','Ricecake','./images/ricecake/',5);
INSERT INTO IDME_GOODS (G_NO, G_NAME, G_CONTENT, G_PRICE, G_TYPE, G_PHOTO, M_NO) VALUES(G_NO_SEQ.NEXTVAL,'떡낭시에','겉바 속촉 휘낭시에? 우리는 겉바속쫀 떡낭시에'||CHR(10)||CHR(13)||''||CHR(10)||CHR(13)||'쫀득하고 든든해요!'||CHR(10)||CHR(13)||'식사대용, 간단한 간식으로 추천','1800','Ricecake','./images/ricecake/',5);
INSERT INTO IDME_GOODS (G_NO, G_NAME, G_CONTENT, G_PRICE, G_TYPE, G_PHOTO, M_NO) VALUES(G_NO_SEQ.NEXTVAL,'꿀설기떡','쫄깃한 백설기 사이사이 달달한 흑당꿀이 아낌없이 들어있어요!!'||CHR(10)||CHR(13)||'흘러넘치듯 많은 양의 꿀이 들어있지만 백설기 자체의 단맛이 적어 너무 달지만은 않아요!!','13000','Ricecake','./images/ricecake/',5);
INSERT INTO IDME_GOODS (G_NO, G_NAME, G_CONTENT, G_PRICE, G_TYPE, G_PHOTO, M_NO) VALUES(G_NO_SEQ.NEXTVAL,'리얼 초코떡','진한 아니고'||CHR(10)||CHR(13)||'정말 찌인~~한 초코크림을 넣은'||CHR(10)||CHR(13)||'찹쌀떡에 바삭한 초코볼을 올려'||CHR(10)||CHR(13)||'고오급스러운 떡을 만들었어요'||CHR(10)||CHR(13)||'.'||CHR(10)||CHR(13)||'.'||CHR(10)||CHR(13)||'팥 싫어하시는분(only 초코크림)'||CHR(10)||CHR(13)||'떡 싫어하시는 분들도 진짜 맛있게 드실수 있는'||CHR(10)||CHR(13)||'떡!!!!!','17500','Ricecake','./images/ricecake/',5);
INSERT INTO IDME_GOODS (G_NO, G_NAME, G_CONTENT, G_PRICE, G_TYPE, G_PHOTO, M_NO) VALUES(G_NO_SEQ.NEXTVAL,'카스텔라 앙쑥떡','쑥 중에서도 명품쑥인 제주도 쑥만 고집합니다.'||CHR(10)||CHR(13)||'절대 그냥 쑥을 섞는다거나 분말, 향료를 넣지 않습니다'||CHR(10)||CHR(13)||'쑥인절미가 아니라 쑥찰떡 입니다 ~! (쑥이 쌀의2배!!)'||CHR(10)||CHR(13)||'저희 쑥찰떡 드셔보신 분들은 아실거에요 ㅎㅎ','22000','Ricecake','./images/ricecake/',5);
INSERT INTO IDME_GOODS (G_NO, G_NAME, G_CONTENT, G_PRICE, G_TYPE, G_PHOTO, M_NO) VALUES(G_NO_SEQ.NEXTVAL,'콩쑥개떡','쫀득쫀득한 식감으로 남녀노소 좋아하는 떡!'||CHR(10)||CHR(13)||'향긋하고 쫄깃한 쑥떡 속에 달콤한 팥앙금을 품었어요.'||CHR(10)||CHR(13)||'바로 고소한 콩가루 옷을 입어 더욱 맛있는 콩쑥개떡입니다.','22000','Ricecake','./images/ricecake/',5);
INSERT INTO IDME_GOODS (G_NO, G_NAME, G_CONTENT, G_PRICE, G_TYPE, G_PHOTO, M_NO) VALUES(G_NO_SEQ.NEXTVAL,'수수부꾸미','수수부꾸미란'||CHR(10)||CHR(13)||'찰수수가루와 찹쌀가루를 섞은 반죽에'||CHR(10)||CHR(13)||'수제 팥앙금을 넣어 노릇하게 구워낸'||CHR(10)||CHR(13)||'찰기 가득한 식감의 달콤 고소한 향토지짐떡입니다.','17500','Ricecake','./images/ricecake/',12);
INSERT INTO IDME_GOODS (G_NO, G_NAME, G_CONTENT, G_PRICE, G_TYPE, G_PHOTO, M_NO) VALUES(G_NO_SEQ.NEXTVAL,'현미곤약가래떡','현미의 풍부한 영양분과'||CHR(10)||CHR(13)||'칼로리가 매우 낮은 곤약이 만나'||CHR(10)||CHR(13)||'부드럽고 쫄깃한 가래떡이 되었어요','14000','Ricecake','./images/ricecake/',12);
INSERT INTO IDME_GOODS (G_NO, G_NAME, G_CONTENT, G_PRICE, G_TYPE, G_PHOTO, M_NO) VALUES(G_NO_SEQ.NEXTVAL,'견과구운찰떡','쫀득한 찰떡과 통팥앙금이 듬뿍 들어간 구운찰떡~!'||CHR(10)||CHR(13)||'오븐에 구워 기름기 걱정 NONO~'||CHR(10)||CHR(13)||'담백하고 쫀득 달콤한 구운찰떡~~!!'||CHR(10)||CHR(13)||'정말정말 맛있어요..','11000','Ricecake','./images/ricecake/',17);
INSERT INTO IDME_GOODS (G_NO, G_NAME, G_CONTENT, G_PRICE, G_TYPE, G_PHOTO, M_NO) VALUES(G_NO_SEQ.NEXTVAL,'딸기모찌','모찌는 받으시면 바로 드시는게 가장 좋습니다'||CHR(10)||CHR(13)||'그러므로 보관후 드시는것 보단 당일 드실수 있는 만큼만 주문 주세요'||CHR(10)||CHR(13)||'냉장 보관은 1~2틀 입니다'||CHR(10)||CHR(13)||'냉동 보관시2주입니다','24000','Ricecake','./images/ricecake/',17);
INSERT INTO IDME_GOODS (G_NO, G_NAME, G_CONTENT, G_PRICE, G_TYPE, G_PHOTO, M_NO) VALUES(G_NO_SEQ.NEXTVAL,'뚱카롱','꼬끄는 필링에 따라 쫀득이거나 빵같은 식감이 들수있어요'||CHR(10)||CHR(13)||'필링에 수분감이 많은 종류는 쫌 더 빵같은 식감을 느낄수있어용( 크림치즈류나 밤 옥수수 쨈유무에 따라 등)'||CHR(10)||CHR(13)||'개별구매도 가능해요'||CHR(10)||CHR(13)||'- 상자 개수에 맞게 구매시 상자 무료'||CHR(10)||CHR(13)||'- 상자 또는 투명 플라스틱케이스(9구만) 구매도 가능합니다','1900','Bread','./images/bread/',18);
INSERT INTO IDME_GOODS (G_NO, G_NAME, G_CONTENT, G_PRICE, G_TYPE, G_PHOTO, M_NO) VALUES(G_NO_SEQ.NEXTVAL,'휘낭쉬에','얼려드시면 2배 맛있는 바멜 휘낭시에'||CHR(10)||CHR(13)||'10개 이상 구매하시고'||CHR(10)||CHR(13)||'<10개 이상 구매 시 박스포장 서비스>'||CHR(10)||CHR(13)||'옵션을 선택해주시면'||CHR(10)||CHR(13)||'위 구성으로 포장해드립니다!','2000','Bread','./images/bread/',18);
INSERT INTO IDME_GOODS (G_NO, G_NAME, G_CONTENT, G_PRICE, G_TYPE, G_PHOTO, M_NO) VALUES(G_NO_SEQ.NEXTVAL,'다이어트 통밀식빵','입이 맛있는것을 넘어'||CHR(10)||CHR(13)||'속이 편한빵을 고민하였습니다.'||CHR(10)||CHR(13)||'수년간의 기술개발을 통해'||CHR(10)||CHR(13)||'거친 통밀을 발아시켜, 통밀의 함량을 높이고'||CHR(10)||CHR(13)||'부드럽게 먹을 수 있는 통밀빵을 만들어냈습니다.','5000','Bread','./images/bread/',13);
INSERT INTO IDME_GOODS (G_NO, G_NAME, G_CONTENT, G_PRICE, G_TYPE, G_PHOTO, M_NO) VALUES(G_NO_SEQ.NEXTVAL,'납짝공갈빵','동그란 공갈빵이 아니라 납짝한 공갈빵입니다~'||CHR(10)||CHR(13)||'한조각 부셔먹으면 입안가득 퍼지는 달달한 끌림~'||CHR(10)||CHR(13)||'더운 날씨에는 냉동실에 넣어놓고'||CHR(10)||CHR(13)||'시원하게 드셔도 맛있답니다','2000','Bread','./images/bread/',13);
INSERT INTO IDME_GOODS (G_NO, G_NAME, G_CONTENT, G_PRICE, G_TYPE, G_PHOTO, M_NO) VALUES(G_NO_SEQ.NEXTVAL,'두툼 수제쿠키','쿠키6종모두담기에 선물포장추가 하신 후'||CHR(10)||CHR(13)||'개별쿠키를 추가해주신경우 한번에 상자포장됩니다!! (10개이하까지)'||CHR(10)||CHR(13)||'따로 필요하신경우엔 꼭 메모에 남겨주세요'||CHR(10)||CHR(13)||'선물포장은 쿠키 갯수에 맞춰 포장됩니다','2500','Bread','./images/bread/',13);
INSERT INTO IDME_GOODS (G_NO, G_NAME, G_CONTENT, G_PRICE, G_TYPE, G_PHOTO, M_NO) VALUES(G_NO_SEQ.NEXTVAL,'소금빵','매일 매장에서 정성껏 구워내는 소금빵입니다.'||CHR(10)||CHR(13)||'매일 매진되는 카페소소한 1위 인기메뉴입니다'||CHR(10)||CHR(13)||'겉은 바삭하고 속은 쫀~득합니다!','2300','Bread','./images/bread/',26);
INSERT INTO IDME_GOODS (G_NO, G_NAME, G_CONTENT, G_PRICE, G_TYPE, G_PHOTO, M_NO) VALUES(G_NO_SEQ.NEXTVAL,'겉바속촉 까눌레','까눌레는 프랑스 수도원에서 만들어졌으며'||CHR(10)||CHR(13)||'카놀이라고 밀가루와 계란 노른자로 만든 과자에서 유래되었습니다'||CHR(10)||CHR(13)||'까눌레는 구운 당일이 지나면'||CHR(10)||CHR(13)||'식감이 조금씩 달라지니 구매시 참고 부탁드리며'||CHR(10)||CHR(13)||'당일 드실것만 남기시고'||CHR(10)||CHR(13)||'나머지는 냉동보관 부탁드릴께요','2500','Bread','./images/bread/',26);
INSERT INTO IDME_GOODS (G_NO, G_NAME, G_CONTENT, G_PRICE, G_TYPE, G_PHOTO, M_NO) VALUES(G_NO_SEQ.NEXTVAL,'조개마카롱세트','일반마카롱에 비해 2배이상 필링이 들어간 조개롱!!!'||CHR(10)||CHR(13)||'생일이나 특별한날 케이크 대신 선물하시기 너무 좋으세요'||CHR(10)||CHR(13)||'원하시는 캐릭터마카롱을 제작해서 보내드립니다'||CHR(10)||CHR(13)||'꼭! 원하시는 캐릭터가 있으시다면 원하시는 이미지를 보내주시면 주문제작 해드려요','23000','Bread','./images/bread/',26);
INSERT INTO IDME_GOODS (G_NO, G_NAME, G_CONTENT, G_PRICE, G_TYPE, G_PHOTO, M_NO) VALUES(G_NO_SEQ.NEXTVAL,'미니 피칸파이','간식으로 너무 좋은 미니호두파이와 피칸파이 입니다'||CHR(10)||CHR(13)||'미니호두파이는'||CHR(10)||CHR(13)||'쫀득하고 촉촉한 식감으로 누구나'||CHR(10)||CHR(13)||'맛있게 드실 수 있고 개별 포장으로 자르지 않고 드실 수 있어서'||CHR(10)||CHR(13)||'누구나 좋아하시는 미니파이 입니다','3000','Bread','./images/bread/',26);
INSERT INTO IDME_GOODS (G_NO, G_NAME, G_CONTENT, G_PRICE, G_TYPE, G_PHOTO, M_NO) VALUES(G_NO_SEQ.NEXTVAL,'레몬쿠키','생 레몬을 직접 짠 레몬 즙과'||CHR(10)||CHR(13)||'제스트가 듬뿍~'||CHR(10)||CHR(13)||'입안에서 느끼는 정말 상큼함을'||CHR(10)||CHR(13)||'느껴보세요','1100','Bread','./images/bread/',19);
INSERT INTO IDME_GOODS (G_NO, G_NAME, G_CONTENT, G_PRICE, G_TYPE, G_PHOTO, M_NO) VALUES(G_NO_SEQ.NEXTVAL,'초콜렛 빨미까레','벨기에산 다크 초콜릿이 코팅된 제품'||CHR(10)||CHR(13)||'다크 초콜릿의 씁쓸하고 달달한 맛과 빨미까레의 바삭함이 잘 어울리는 제품'||CHR(10)||CHR(13)||'단 걸 좋아하지만 너무 단걸 좋아하지 않는 분들에게 추천!!','3900','Bread','./images/bread/',19);
INSERT INTO IDME_GOODS (G_NO, G_NAME, G_CONTENT, G_PRICE, G_TYPE, G_PHOTO, M_NO) VALUES(G_NO_SEQ.NEXTVAL,'100% 우리밀 미니크랜베리빵','어린 아이들도 먹기 편한 미니 사이즈의 식빵입니다.'||CHR(10)||CHR(13)||'강한 맛이 아닌 자연 그대로의 맛을 담았습니다.'||CHR(10)||CHR(13)||'탕종으로 만들어 빵이 쫀득합니다.'||CHR(10)||CHR(13)||'크랜베리가 들어있어서 새콤달콤합니다.','5000','Bread','./images/bread/',24);
INSERT INTO IDME_GOODS (G_NO, G_NAME, G_CONTENT, G_PRICE, G_TYPE, G_PHOTO, M_NO) VALUES(G_NO_SEQ.NEXTVAL,'리얼딸기 생초콜릿','당당하게 인사드립니다'||CHR(10)||CHR(13)||'눈이 행복한 비주얼'||CHR(10)||CHR(13)||'딸기향에 한번 반하고'||CHR(10)||CHR(13)||'딸기맛에 한번더 반하는'||CHR(10)||CHR(13)||'리얼딸기 생초콜릿'||CHR(10)||CHR(13)||CHR(10)||CHR(13)||'고급커버춰 벨기에산 딸기초콜릿'||CHR(10)||CHR(13)||'추가적으로'||CHR(10)||CHR(13)||'동결 생딸기 다이스를 듬뿍듬뿍'||CHR(10)||CHR(13)||'동결 생딸기 분말 듬뿍듬뿍','4900','Chocolate','./images/chocolate/',24);
INSERT INTO IDME_GOODS (G_NO, G_NAME, G_CONTENT, G_PRICE, G_TYPE, G_PHOTO, M_NO) VALUES(G_NO_SEQ.NEXTVAL,'수제초콜릿 아망드쇼콜라','다크,밀크 아망드 쇼콜라는'||CHR(10)||CHR(13)||'파우더 제품으로 출고됩니다.'||CHR(10)||CHR(13)||CHR(10)||CHR(13)||'인공색소를 사용하지 않으며,'||CHR(10)||CHR(13)||'100% 천연파우더입니다.(흑임자, 단호박)'||CHR(10)||CHR(13)||CHR(10)||CHR(13)||'당도 : 흑임자, 단호박 아망드쇼콜라는'||CHR(10)||CHR(13)||'화이트 초콜릿을 사용하므로 당도가 높습니다.'||CHR(10)||CHR(13)||'당도가 높은 제품을 싫어하시는분은 다크를 추천합니다.','4500','Chocolate','./images/chocolate/',24);
INSERT INTO IDME_GOODS (G_NO, G_NAME, G_CONTENT, G_PRICE, G_TYPE, G_PHOTO, M_NO) VALUES(G_NO_SEQ.NEXTVAL,'민트 아보카도초콜릿','화이트초콜릿으로 만든 두가지의 민트가나슈를'||CHR(10)||CHR(13)||'그라데이션을 주어 아보카도의 속살을 표현했어요!'||CHR(10)||CHR(13)||CHR(10)||CHR(13)||'아보카도의 씨앗속에는 다크초콜릿 민트가나슈가'||CHR(10)||CHR(13)||'들어있어요!!'||CHR(10)||CHR(13)||CHR(10)||CHR(13)||'아보카도의 껍질은 다크초콜릿으로'||CHR(10)||CHR(13)||'씨앗의 껍데기는 밀크초콜릿으로 만들어졌답니다.','7500','Chocolate','./images/chocolate/',10);
INSERT INTO IDME_GOODS (G_NO, G_NAME, G_CONTENT, G_PRICE, G_TYPE, G_PHOTO, M_NO) VALUES(G_NO_SEQ.NEXTVAL,'복숭아 생초콜릿','향긋하고 달콤한 사계절 복숭아 생초콜릿'||CHR(10)||CHR(13)||CHR(10)||CHR(13)||'그동안 여름철 짧게 만나서 아쉬웠던 복숭아를'||CHR(10)||CHR(13)||'사계절 내내 시원하고 달콤한 생 초콜릿으로 담아내고 싶었습니다'||CHR(10)||CHR(13)||CHR(10)||CHR(13)||'수확의계절 만의 특별한 레시피로 만든 수제 복숭아 생초콜릿','7500','Chocolate','./images/chocolate/',10);
INSERT INTO IDME_GOODS (G_NO, G_NAME, G_CONTENT, G_PRICE, G_TYPE, G_PHOTO, M_NO) VALUES(G_NO_SEQ.NEXTVAL,'하리보 초콜릿','최상급의 재료를 사용'||CHR(10)||CHR(13)||'모든제품을 직접만들어 정성을 다하는 제품'||CHR(10)||CHR(13)||'수많은 다양한 커버춰를 한번에 맛볼 수 있는 제품'||CHR(10)||CHR(13)||'병무게를 제외하고 약 50g 정도로 넉넉한 양','6000','Chocolate','./images/chocolate/',10);
INSERT INTO IDME_GOODS (G_NO, G_NAME, G_CONTENT, G_PRICE, G_TYPE, G_PHOTO, M_NO) VALUES(G_NO_SEQ.NEXTVAL,'민트초코오레오 판초콜릿','오레오 과자와 민트시럽이 들어간'||CHR(10)||CHR(13)||'민트 오레오 판 초콜릿 입니다!'||CHR(10)||CHR(13)||CHR(10)||CHR(13)||'질 좋은 화이트 커버춰 초콜릿으로 정성스럽게 만듭니다'||CHR(10)||CHR(13)||CHR(10)||CHR(13)||'민트 매니아 분들에게 취향저격인 초콜릿입니다!','6500','Chocolate','./images/chocolate/',23);
INSERT INTO IDME_GOODS (G_NO, G_NAME, G_CONTENT, G_PRICE, G_TYPE, G_PHOTO, M_NO) VALUES(G_NO_SEQ.NEXTVAL,'귤칩 초콜릿','추운겨울 비타민도 보충하고'||CHR(10)||CHR(13)||'당충전도 할수있는'||CHR(10)||CHR(13)||'새콤달콤 겨울한정메뉴'||CHR(10)||CHR(13)||'라즐리 귤칩 초콜릿입니다.'||CHR(10)||CHR(13)||CHR(10)||CHR(13)||'깨끗하게 세척한 제주감귤을 건조기에 건조하여'||CHR(10)||CHR(13)||'벨기에 다크초콜릿or'||CHR(10)||CHR(13)||'벨기에 화이트초콜릿 에 디핑하였습니다.','2500','Chocolate','./images/chocolate/',23);
INSERT INTO IDME_GOODS (G_NO, G_NAME, G_CONTENT, G_PRICE, G_TYPE, G_PHOTO, M_NO) VALUES(G_NO_SEQ.NEXTVAL,'초콜릿오랑제뜨','멜리 초콜릿 오랑제뜨 (오렌지/레몬)'||CHR(10)||CHR(13)||'특별한 날,'||CHR(10)||CHR(13)||'특별하지 않은 여느날에도'||CHR(10)||CHR(13)||'소중한 사람에게'||CHR(10)||CHR(13)||'달콤함을 선물하고 싶을 때.'||CHR(10)||CHR(13)||CHR(10)||CHR(13)||'선물 하는 사람,'||CHR(10)||CHR(13)||'선물 받는 사람 모두가'||CHR(10)||CHR(13)||'행복해졌음 하는 마음에'||CHR(10)||CHR(13)||'‘멜리 초콜릿’이 만들어지게 되었습니다','12800','Chocolate','./images/chocolate/',15);
INSERT INTO IDME_GOODS (G_NO, G_NAME, G_CONTENT, G_PRICE, G_TYPE, G_PHOTO, M_NO) VALUES(G_NO_SEQ.NEXTVAL,'황치즈 생초콜릿','깊고 진한 치즈의 맛과 향치즈와 초콜릿 단짠단짠의 정석'||CHR(10)||CHR(13)||'한 입 베어물면 부드럽게 녹아드는 식감','13000','Chocolate','./images/chocolate/',15);
INSERT INTO IDME_GOODS (G_NO, G_NAME, G_CONTENT, G_PRICE, G_TYPE, G_PHOTO, M_NO) VALUES(G_NO_SEQ.NEXTVAL,'오너먼트볼 초콜릿','이번에는 크리스마스트리에 장식 할 수 있는'||CHR(10)||CHR(13)||'오너먼트 볼 모양의 초콜릿을 준비해보았답니다'||CHR(10)||CHR(13)||CHR(10)||CHR(13)||'볼 하나하나 정성스럽게 포장해서 실제 장식으로'||CHR(10)||CHR(13)||'사용하실 수 있게 고리를 달아서 제작하여 드립니다','10000','Chocolate','./images/chocolate/',15);
INSERT INTO IDME_GOODS (G_NO, G_NAME, G_CONTENT, G_PRICE, G_TYPE, G_PHOTO, M_NO) VALUES(G_NO_SEQ.NEXTVAL,'자일리톨 스톤캔디','이런분에게 추천해요'||CHR(10)||CHR(13)||'달콤한 에너지가 필요한 직장인'||CHR(10)||CHR(13)||'졸음운전이 걱정인 기사님'||CHR(10)||CHR(13)||'오늘도 배고픈 다이어터'||CHR(10)||CHR(13)||'예쁜 아이를 가진 임산부'||CHR(10)||CHR(13)||'양치 교육이 필요한 아이'||CHR(10)||CHR(13)||CHR(10)||CHR(13)||'무려 21가지 맛으로 준비했어요'||CHR(10)||CHR(13)||'취향껏 고르세요!','6700','Candy','./images/candy/',20);
INSERT INTO IDME_GOODS (G_NO, G_NAME, G_CONTENT, G_PRICE, G_TYPE, G_PHOTO, M_NO) VALUES(G_NO_SEQ.NEXTVAL,'안정사탕','캐모마일 꽃을 입에 머금은 듯 스르르 녹아'||CHR(10)||CHR(13)||'달콤한 맛에 꽃 향이 머무는 수제사탕입니다.'||CHR(10)||CHR(13)||CHR(10)||CHR(13)||'잠이 잘 안 와서 캐모마일을 먹고 싶은데 맛있게 먹고 싶은'||CHR(10)||CHR(13)||'사람들에게도, 걱정과 고민이 많아 우울하거나 응원해주고'||CHR(10)||CHR(13)||'싶은 소중한 사람들에게 특별하고'||CHR(10)||CHR(13)||'좋은 선물이 될 수 있습니다','12000','Candy','./images/candy/',20);
INSERT INTO IDME_GOODS (G_NO, G_NAME, G_CONTENT, G_PRICE, G_TYPE, G_PHOTO, M_NO) VALUES(G_NO_SEQ.NEXTVAL,'플라워캔디','오늘 소개해드릴 작품은 실사 뮬리를 담은'||CHR(10)||CHR(13)||'Pink flower Candy입니다'||CHR(10)||CHR(13)||CHR(10)||CHR(13)||'우닉의 top5에 속하는 사탕이고'||CHR(10)||CHR(13)||'사계절 상관없이 특별한날, 선물하기에 정말좋아요','19800','Candy','./images/candy/',20);
INSERT INTO IDME_GOODS (G_NO, G_NAME, G_CONTENT, G_PRICE, G_TYPE, G_PHOTO, M_NO) VALUES(G_NO_SEQ.NEXTVAL,'갤럭시캔디','빛나는 은하계를 담은'||CHR(10)||CHR(13)||'Blue galaxy 사탕이에요'||CHR(10)||CHR(13)||'그린애플(greenapple)'||CHR(10)||CHR(13)||'6개모두 동일맛입니다','17200','Candy','./images/candy/',22);
INSERT INTO IDME_GOODS (G_NO, G_NAME, G_CONTENT, G_PRICE, G_TYPE, G_PHOTO, M_NO) VALUES(G_NO_SEQ.NEXTVAL,'이모지캔디','12가지의 다양한 표정의 이모션 캔디입니다'||CHR(10)||CHR(13)||'귀여운 모양의 이모티콘을 떠올리며 제작해보았어요'||CHR(10)||CHR(13)||'12입,6개입 모두 레몬(lemon) 동일맛입니다','19800','Candy','./images/candy/',22);
INSERT INTO IDME_GOODS (G_NO, G_NAME, G_CONTENT, G_PRICE, G_TYPE, G_PHOTO, M_NO) VALUES(G_NO_SEQ.NEXTVAL,'롤솜사탕','솜사탕 5개를 압축해 롤케익처럼'||CHR(10)||CHR(13)||'말아서 만든 수제 솜사탕 입니다.'||CHR(10)||CHR(13)||'5번을 말아 만드는 것이라'||CHR(10)||CHR(13)||'일반 솜사탕에 비해'||CHR(10)||CHR(13)||'시간과 정성이 많이 들어가요~','6000','Candy','./images/candy/',22);
INSERT INTO IDME_GOODS (G_NO, G_NAME, G_CONTENT, G_PRICE, G_TYPE, G_PHOTO, M_NO) VALUES(G_NO_SEQ.NEXTVAL,'핑거볼 후르츠 수제캔디','핑거볼 후르츠 수제캔디'||CHR(10)||CHR(13)||'[ 맛 ]'||CHR(10)||CHR(13)||'노랑 - 망고'||CHR(10)||CHR(13)||'파랑 - 포도'||CHR(10)||CHR(13)||' (best) 빨강- 바나나+파인애플'||CHR(10)||CHR(13)||CHR(10)||CHR(13)||'다양한 모양과 과일맛 캔디를'||CHR(10)||CHR(13)||'골라먹는 재미가 쏠쏠~','9000','Candy','./images/candy/',4);
INSERT INTO IDME_GOODS (G_NO, G_NAME, G_CONTENT, G_PRICE, G_TYPE, G_PHOTO, M_NO) VALUES(G_NO_SEQ.NEXTVAL,'크리스마스 롤리팝','크리스마스하면 떠오르는 빨강색,초록색으로'||CHR(10)||CHR(13)||'포인트를주어 만든 크리스마스 롤리팝입니다'||CHR(10)||CHR(13)||CHR(10)||CHR(13)||'크리스마스 시즌에만 구매가 가능한'||CHR(10)||CHR(13)||'특별한 수제사탕입니다','2000','Candy','./images/candy/',4);
INSERT INTO IDME_GOODS (G_NO, G_NAME, G_CONTENT, G_PRICE, G_TYPE, G_PHOTO, M_NO) VALUES(G_NO_SEQ.NEXTVAL,'강릉커피사탕','강릉커피사탕은 상위 10%내의 착한원두를 선별'||CHR(10)||CHR(13)||'커피장인들의 로스팅을 거쳐 추출한 에스프레소와'||CHR(10)||CHR(13)||'유기농비정제설탕,유기농우유,유기농코코넛오일등'||CHR(10)||CHR(13)||'건강한 재료들로 한알 한알 빚어낸'||CHR(10)||CHR(13)||'`유기농 순수커피사탕`입니다?','8000','Candy','./images/candy/',4);
INSERT INTO IDME_GOODS (G_NO, G_NAME, G_CONTENT, G_PRICE, G_TYPE, G_PHOTO, M_NO) VALUES(G_NO_SEQ.NEXTVAL,'사탕 꽃다발','별처럼 빛나는 사탕꽃다발'||CHR(10)||CHR(13)||'이쁘게 작업해서 출고하고 있습니다'||CHR(10)||CHR(13)||'제가 당일에 출고를 해도 배송 같은 경우는'||CHR(10)||CHR(13)||'택배사에서 물량이나 날씨영향을 많이 받기때문에'||CHR(10)||CHR(13)||'혹시 늦어질 수 있는점 참고해서 주문 주시기 바랍니다'||CHR(10)||CHR(13)||'소재. 비누꽃, 미스티블루(드라이플라워)','4850','Candy','./images/candy/',4);
INSERT INTO IDME_GOODS (G_NO, G_NAME, G_CONTENT, G_PRICE, G_TYPE, G_PHOTO, M_NO) VALUES(G_NO_SEQ.NEXTVAL,'마카롱케이크','달달지다 마카롱은 입자가 굵은 아몬드가루로'||CHR(10)||CHR(13)||'꼬끄표면이 다소 거칠수 있으나좋은 재료를'||CHR(10)||CHR(13)||'사용한다는 신념하에 누구나 안심하고 드실 수'||CHR(10)||CHR(13)||'있습니다. 달달지다만의 꼬끄를 만드는 방식 및'||CHR(10)||CHR(13)||'필링과의 숙성 과정으로 쫀득쫀득한 식감의'||CHR(10)||CHR(13)||'마카롱을 자부합니다.','19900','Cake','./images/cake/',11);
INSERT INTO IDME_GOODS (G_NO, G_NAME, G_CONTENT, G_PRICE, G_TYPE, G_PHOTO, M_NO) VALUES(G_NO_SEQ.NEXTVAL,'마틸다케이크','꾸덕한 진짜 초콜릿으로 만든 마성의 케이크 마틸다 레터링 케이크'||CHR(10)||CHR(13)||'영화 마틸다에서 가장 집중해서 보았던 씬 속의 그 케이크.'||CHR(10)||CHR(13)||'바로 마틸다 케이크가 레터링 케이크로 탄생했어요.'||CHR(10)||CHR(13)||CHR(10)||CHR(13)||'진한 초콜릿 시트에 깊은 풍미의 쇼콜라 가나슈가'||CHR(10)||CHR(13)||'악마의 케이크의 맛을 그대로 느끼게 해준답니다.','26000','Cake','./images/cake/',11);
INSERT INTO IDME_GOODS (G_NO, G_NAME, G_CONTENT, G_PRICE, G_TYPE, G_PHOTO, M_NO) VALUES(G_NO_SEQ.NEXTVAL,'미니생크림 케이크','신선한 우유향 가득한~'||CHR(10)||CHR(13)||'부드럽고 촉촉한 순우유 생크림 케이크'||CHR(10)||CHR(13)||CHR(10)||CHR(13)||'시트에서 느껴지는 폭신폭신함!'||CHR(10)||CHR(13)||'너무 부드러워서 입 안에서 사르르 녹아요~'||CHR(10)||CHR(13)||CHR(10)||CHR(13)||'서울브레드 수제 케이크로 특별한 하루를 선물하세요.','6700','Cake','./images/cake/',11);
INSERT INTO IDME_GOODS (G_NO, G_NAME, G_CONTENT, G_PRICE, G_TYPE, G_PHOTO, M_NO) VALUES(G_NO_SEQ.NEXTVAL,'딸기폭탄케이크','딸기가 듬뿍 들어간'||CHR(10)||CHR(13)||'100% 동물성생크림으로 만든 케이크'||CHR(10)||CHR(13)||CHR(10)||CHR(13)||'포켓파크는 자극적인 맛을 지양하고'||CHR(10)||CHR(13)||'재료 본연의 은은한 맛을 지향하기 때문에'||CHR(10)||CHR(13)||'당함량은 낮추고 일체의 색소 또는'||CHR(10)||CHR(13)||'화학 첨가제를 사용하지 않아요.','25000','Cake','./images/cake/',11);
INSERT INTO IDME_GOODS (G_NO, G_NAME, G_CONTENT, G_PRICE, G_TYPE, G_PHOTO, M_NO) VALUES(G_NO_SEQ.NEXTVAL,'밀크레이프케이크','크림이 층층이 쌓인 밀크레이프 케이크'||CHR(10)||CHR(13)||CHR(10)||CHR(13)||'우유, 계란, 설탕, 밀가루, 전분, 버터'||CHR(10)||CHR(13)||'그리고 고급 바닐라빈을 넣고 매장에서 직접 끓여 만든 크림과'||CHR(10)||CHR(13)||'100% 우유 생크림을 혼합해 만들어요.','21000','Cake','./images/cake/',11);
INSERT INTO IDME_GOODS (G_NO, G_NAME, G_CONTENT, G_PRICE, G_TYPE, G_PHOTO, M_NO) VALUES(G_NO_SEQ.NEXTVAL,'플라워리스케이크','플라워 리스형태의 사랑스러운 디자인입니다.'||CHR(10)||CHR(13)||'부케형식이 조금 부담스러우신 분들 여백이 있는걸 좋아하시는 분들이 선호하시는 디자인이에요'||CHR(10)||CHR(13)||CHR(10)||CHR(13)||'모든 설기는 건강한 재료로 직접 당일 생산합니다^^'||CHR(10)||CHR(13)||'요청사항에 원하시는 필링을 꼭꼭!!!적어주세요-^^'||CHR(10)||CHR(13)||CHR(10)||CHR(13)||'모든 설기는 견과류와 필링을 뺄 수 있어요^^','50000','Cake','./images/cake/',6);
INSERT INTO IDME_GOODS (G_NO, G_NAME, G_CONTENT, G_PRICE, G_TYPE, G_PHOTO, M_NO) VALUES(G_NO_SEQ.NEXTVAL,'미니쌀케익','100%국산쌀가루를 사용해서 만든 쌀케이크입니다.'||CHR(10)||CHR(13)||'정미소는 소량의 베이킹파우더와 레터링에 필요한 식용색소를 제외한 합성첨가물은 전혀 사용하지 않습니다.'||CHR(10)||CHR(13)||'정미소의 케이크는 마다가스카르산 천연바닐라빈, 코앵트로(오렌지리큐르), 천연 계피가루, 제주산 친환경 레몬필 등을 사용하여 향을 더욱 풍부하게 만듭니다.','10500','Cake','./images/cake/',6);
INSERT INTO IDME_GOODS (G_NO, G_NAME, G_CONTENT, G_PRICE, G_TYPE, G_PHOTO, M_NO) VALUES(G_NO_SEQ.NEXTVAL,'초코롤케익','유지방분이 높은 고급 생크림만을 사용하여 고급스럽고 은은한 단맛이 느껴집니다.'||CHR(10)||CHR(13)||'크림치즈가 45%나 함량되어 더욱 고소하고 부드럽습니다.'||CHR(10)||CHR(13)||'오븐에서 최상의 맛을 만들어낼 온도를 여러 테스트를 걸쳐 연구해 찾아냈습니다.','22500','Cake','./images/cake/',6);
INSERT INTO IDME_GOODS (G_NO, G_NAME, G_CONTENT, G_PRICE, G_TYPE, G_PHOTO, M_NO) VALUES(G_NO_SEQ.NEXTVAL,'미니컵 바스크 치즈케이크','치즈풍미가 너무 찐~해서 큰 거 한판 드시기엔'||CHR(10)||CHR(13)||'부담스러운 분들을 위해!'||CHR(10)||CHR(13)||'먹기좋게 머핀컵 크기로 구워봤어요 :)'||CHR(10)||CHR(13)||CHR(10)||CHR(13)||'혼자 먹기좋은 1인용 바스크치즈케이크','3800','Cake','./images/cake/',16);
INSERT INTO IDME_GOODS (G_NO, G_NAME, G_CONTENT, G_PRICE, G_TYPE, G_PHOTO, M_NO) VALUES(G_NO_SEQ.NEXTVAL,'얼그레이케이크','생크림을 바르거나 채워 넣는 제품이 아니라'||CHR(10)||CHR(13)||'설탕코팅(아이싱)으로 보존효과를 더해서'||CHR(10)||CHR(13)||'쉽게 상하지 않으니 염려마세요.'||CHR(10)||CHR(13)||CHR(10)||CHR(13)||'위에 뿌린 슈가글라사쥬는 크림이 아닌 홍차와 설탕반죽을 오븐열로 굳힌 설탕코팅이예요.','2800','Cake','./images/cake/',16);


-- PHOTO INSERT

INSERT INTO IDME_PHOTOS VALUES (1, '/images/ricecake/', 1, '1_001.jpg');
INSERT INTO IDME_PHOTOS VALUES (1, '/images/ricecake/', 2, '1_002.jpg');
INSERT INTO IDME_PHOTOS VALUES (2, '/images/ricecake/', 1, '2_001.jpg');
INSERT INTO IDME_PHOTOS VALUES (2, '/images/ricecake/', 2, '2_002.jpg');
INSERT INTO IDME_PHOTOS VALUES (3, '/images/ricecake/', 1, '3_001.jpg');
INSERT INTO IDME_PHOTOS VALUES (3, '/images/ricecake/', 2, '3_002.jpg');
INSERT INTO IDME_PHOTOS VALUES (4, '/images/ricecake/', 1, '4_001.jpg');
INSERT INTO IDME_PHOTOS VALUES (4, '/images/ricecake/', 2, '4_002.jpg');
INSERT INTO IDME_PHOTOS VALUES (5, '/images/ricecake/', 1, '5_001.jpg');
INSERT INTO IDME_PHOTOS VALUES (5, '/images/ricecake/', 2, '5_002.jpg');
INSERT INTO IDME_PHOTOS VALUES (6, '/images/ricecake/', 1, '6_001.jpg');
INSERT INTO IDME_PHOTOS VALUES (6, '/images/ricecake/', 2, '6_002.jpg');
INSERT INTO IDME_PHOTOS VALUES (7, '/images/ricecake/', 1, '7_001.jpg');
INSERT INTO IDME_PHOTOS VALUES (7, '/images/ricecake/', 2, '7_002.jpg');
INSERT INTO IDME_PHOTOS VALUES (8, '/images/ricecake/', 1, '8_001.jpg');
INSERT INTO IDME_PHOTOS VALUES (8, '/images/ricecake/', 2, '8_002.jpg');
INSERT INTO IDME_PHOTOS VALUES (9, '/images/ricecake/', 1, '9_001.jpg');
INSERT INTO IDME_PHOTOS VALUES (9, '/images/ricecake/', 2, '9_002.jpg');
INSERT INTO IDME_PHOTOS VALUES (10, '/images/ricecake/', 1, '10_001.jpg');
INSERT INTO IDME_PHOTOS VALUES (10, '/images/ricecake/', 2, '10_002.jpg');
INSERT INTO IDME_PHOTOS VALUES (11, '/images/bread/', 1, '11_001.jpg');
INSERT INTO IDME_PHOTOS VALUES (11, '/images/bread/', 2, '11_002.jpg');
INSERT INTO IDME_PHOTOS VALUES (12, '/images/bread/', 1, '12_001.jpg');
INSERT INTO IDME_PHOTOS VALUES (12, '/images/bread/', 2, '12_002.jpg');
INSERT INTO IDME_PHOTOS VALUES (13, '/images/bread/', 1, '13_001.jpg');
INSERT INTO IDME_PHOTOS VALUES (13, '/images/bread/', 2, '13_002.jpg');
INSERT INTO IDME_PHOTOS VALUES (14, '/images/bread/', 1, '14_001.jpg');
INSERT INTO IDME_PHOTOS VALUES (14, '/images/bread/', 2, '14_002.jpg');
INSERT INTO IDME_PHOTOS VALUES (15, '/images/bread/', 1, '15_001.jpg');
INSERT INTO IDME_PHOTOS VALUES (15, '/images/bread/', 2, '15_002.jpg');
INSERT INTO IDME_PHOTOS VALUES (16, '/images/bread/', 1, '16_001.jpg');
INSERT INTO IDME_PHOTOS VALUES (16, '/images/bread/', 2, '16_002.jpg');
INSERT INTO IDME_PHOTOS VALUES (17, '/images/bread/', 1, '17_001.jpg');
INSERT INTO IDME_PHOTOS VALUES (17, '/images/bread/', 2, '17_002.jpg');
INSERT INTO IDME_PHOTOS VALUES (18, '/images/bread/', 1, '18_001.jpg');
INSERT INTO IDME_PHOTOS VALUES (18, '/images/bread/', 2, '18_002.jpg');
INSERT INTO IDME_PHOTOS VALUES (19, '/images/bread/', 1, '19_001.jpg');
INSERT INTO IDME_PHOTOS VALUES (19, '/images/bread/', 2, '19_002.jpg');
INSERT INTO IDME_PHOTOS VALUES (20, '/images/bread/', 1, '20_001.jpg');
INSERT INTO IDME_PHOTOS VALUES (20, '/images/bread/', 2, '20_002.jpg');
INSERT INTO IDME_PHOTOS VALUES (21, '/images/bread/', 1, '21_001.jpg');
INSERT INTO IDME_PHOTOS VALUES (21, '/images/bread/', 2, '21_002.jpg');
INSERT INTO IDME_PHOTOS VALUES (22, '/images/bread/', 1, '22_001.jpg');
INSERT INTO IDME_PHOTOS VALUES (22, '/images/bread/', 2, '22_002.jpg');
INSERT INTO IDME_PHOTOS VALUES (23, '/images/chocolate/', 1, '23_001.jpg');
INSERT INTO IDME_PHOTOS VALUES (23, '/images/chocolate/', 2, '23_002.jpg');
INSERT INTO IDME_PHOTOS VALUES (24, '/images/chocolate/', 1, '24_001.jpg');
INSERT INTO IDME_PHOTOS VALUES (24, '/images/chocolate/', 2, '24_002.jpg');
INSERT INTO IDME_PHOTOS VALUES (25, '/images/chocolate/', 1, '25_001.jpg');
INSERT INTO IDME_PHOTOS VALUES (25, '/images/chocolate/', 2, '25_002.jpg');
INSERT INTO IDME_PHOTOS VALUES (26, '/images/chocolate/', 1, '26_001.jpg');
INSERT INTO IDME_PHOTOS VALUES (26, '/images/chocolate/', 2, '26_002.jpg');
INSERT INTO IDME_PHOTOS VALUES (27, '/images/chocolate/', 1, '27_001.jpg');
INSERT INTO IDME_PHOTOS VALUES (27, '/images/chocolate/', 2, '27_002.jpg');
INSERT INTO IDME_PHOTOS VALUES (28, '/images/chocolate/', 1, '28_001.jpg');
INSERT INTO IDME_PHOTOS VALUES (28, '/images/chocolate/', 2, '28_002.jpg');
INSERT INTO IDME_PHOTOS VALUES (29, '/images/chocolate/', 1, '29_001.jpg');
INSERT INTO IDME_PHOTOS VALUES (29, '/images/chocolate/', 2, '29_002.jpg');
INSERT INTO IDME_PHOTOS VALUES (30, '/images/chocolate/', 1, '30_001.jpg');
INSERT INTO IDME_PHOTOS VALUES (30, '/images/chocolate/', 2, '30_002.jpg');
INSERT INTO IDME_PHOTOS VALUES (31, '/images/chocolate/', 1, '31_001.jpg');
INSERT INTO IDME_PHOTOS VALUES (31, '/images/chocolate/', 2, '31_002.jpg');
INSERT INTO IDME_PHOTOS VALUES (32, '/images/chocolate/', 1, '32_001.jpg');
INSERT INTO IDME_PHOTOS VALUES (32, '/images/chocolate/', 2, '32_002.jpg');
INSERT INTO IDME_PHOTOS VALUES (33, '/images/candy/', 1, '33_001.jpg');
INSERT INTO IDME_PHOTOS VALUES (33, '/images/candy/', 2, '33_002.jpg');
INSERT INTO IDME_PHOTOS VALUES (34, '/images/candy/', 1, '34_001.jpg');
INSERT INTO IDME_PHOTOS VALUES (34, '/images/candy/', 2, '34_002.jpg');
INSERT INTO IDME_PHOTOS VALUES (35, '/images/candy/', 1, '35_001.jpg');
INSERT INTO IDME_PHOTOS VALUES (35, '/images/candy/', 2, '35_002.jpg');
INSERT INTO IDME_PHOTOS VALUES (36, '/images/candy/', 1, '36_001.jpg');
INSERT INTO IDME_PHOTOS VALUES (36, '/images/candy/', 2, '36_002.jpg');
INSERT INTO IDME_PHOTOS VALUES (37, '/images/candy/', 1, '37_001.jpg');
INSERT INTO IDME_PHOTOS VALUES (37, '/images/candy/', 2, '37_002.jpg');
INSERT INTO IDME_PHOTOS VALUES (38, '/images/candy/', 1, '38_001.jpg');
INSERT INTO IDME_PHOTOS VALUES (38, '/images/candy/', 2, '38_002.jpg');
INSERT INTO IDME_PHOTOS VALUES (39, '/images/candy/', 1, '39_001.jpg');
INSERT INTO IDME_PHOTOS VALUES (39, '/images/candy/', 2, '39_002.jpg');
INSERT INTO IDME_PHOTOS VALUES (40, '/images/candy/', 1, '40_001.jpg');
INSERT INTO IDME_PHOTOS VALUES (40, '/images/candy/', 2, '40_002.jpg');
INSERT INTO IDME_PHOTOS VALUES (41, '/images/candy/', 1, '41_001.jpg');
INSERT INTO IDME_PHOTOS VALUES (41, '/images/candy/', 2, '41_002.jpg');
INSERT INTO IDME_PHOTOS VALUES (42, '/images/candy/', 1, '42_001.jpg');
INSERT INTO IDME_PHOTOS VALUES (42, '/images/candy/', 2, '42_002.jpg');
INSERT INTO IDME_PHOTOS VALUES (43, '/images/cake/', 1, '43_001.jpg');
INSERT INTO IDME_PHOTOS VALUES (43, '/images/cake/', 2, '43_002.jpg');
INSERT INTO IDME_PHOTOS VALUES (44, '/images/cake/', 1, '44_001.jpg');
INSERT INTO IDME_PHOTOS VALUES (44, '/images/cake/', 2, '44_002.jpg');
INSERT INTO IDME_PHOTOS VALUES (45, '/images/cake/', 1, '45_001.jpg');
INSERT INTO IDME_PHOTOS VALUES (45, '/images/cake/', 2, '45_002.jpg');
INSERT INTO IDME_PHOTOS VALUES (46, '/images/cake/', 1, '46_001.jpg');
INSERT INTO IDME_PHOTOS VALUES (46, '/images/cake/', 2, '46_002.jpg');
INSERT INTO IDME_PHOTOS VALUES (47, '/images/cake/', 1, '47_001.jpg');
INSERT INTO IDME_PHOTOS VALUES (47, '/images/cake/', 2, '47_002.jpg');
INSERT INTO IDME_PHOTOS VALUES (48, '/images/cake/', 1, '48_001.jpg');
INSERT INTO IDME_PHOTOS VALUES (48, '/images/cake/', 2, '48_002.jpg');
INSERT INTO IDME_PHOTOS VALUES (49, '/images/cake/', 1, '49_001.jpg');
INSERT INTO IDME_PHOTOS VALUES (49, '/images/cake/', 2, '49_002.jpg');
INSERT INTO IDME_PHOTOS VALUES (50, '/images/cake/', 1, '50_001.jpg');
INSERT INTO IDME_PHOTOS VALUES (50, '/images/cake/', 2, '50_002.jpg');
INSERT INTO IDME_PHOTOS VALUES (51, '/images/cake/', 1, '51_001.jpg');
INSERT INTO IDME_PHOTOS VALUES (51, '/images/cake/', 2, '51_002.jpg');
INSERT INTO IDME_PHOTOS VALUES (52, '/images/cake/', 1, '52_001.jpg');
INSERT INTO IDME_PHOTOS VALUES (52, '/images/cake/', 2, '52_002.jpg');

commit;
